on:
  push:
    branches:
      - master
name: 🚀 Deploy - Ambiente de Produção
jobs:
  dev:
    name: 🌐 Deploy - gwouvidoria.com.br
    runs-on: ubuntu-latest
    steps:
      - name: 🔎 Verificando Diretório
        uses: actions/checkout@v3

      - name: 📂 Sincronizando Arquivos
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: public_html/

      - name: ▶️ Executando Scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          script: 'cd /home/gwouvidoria/public_html && php artisan migrate --force && php artisan optimize:clear && php artisan route:cache'
